version: '3.1'
services:

  postgres:
    image: postgres:12.5
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
